#!/bin/bash
#
# TeslaUSB Shell Configuration Wrapper
#
# This file loads configuration from config.yaml using python3.
# DO NOT EDIT THIS FILE - edit config.yaml instead.
#
# This wrapper provides bash variables from YAML for all shell scripts.
#

# Determine the location of this script
SCRIPT_DIR_CONFIG="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Determine config.yaml location (one level up from scripts/)
if [[ "$SCRIPT_DIR_CONFIG" == */scripts ]]; then
  CONFIG_YAML="$(dirname "$SCRIPT_DIR_CONFIG")/config.yaml"
else
  # If sourced from root directory script
  CONFIG_YAML="$SCRIPT_DIR_CONFIG/config.yaml"
fi

# Verify config.yaml exists
if [ ! -f "$CONFIG_YAML" ]; then
  echo "ERROR: Configuration file not found at $CONFIG_YAML" >&2
  exit 1
fi

# PERFORMANCE OPTIMIZATION: Call python3 ONCE and parse all values
# Using shlex.quote() for safe shell variable output (prevents injection attacks)
eval "$(python3 - "$CONFIG_YAML" <<'PYEOF'
import sys, yaml, shlex

def q(v):
    return shlex.quote('' if v is None else str(v))

def b(v):
    return 'true' if v else 'false'

try:
    with open(sys.argv[1]) as f:
        c = yaml.safe_load(f)
except Exception as e:
    sys.stderr.write(f'ERROR: Failed to parse config.yaml: {e}\n')
    sys.exit(1)

inst  = c.get('installation', {})
disk  = c.get('disk_images', {})
setup = c.get('setup', {})
net   = c.get('network', {})
ap    = c.get('offline_ap', {})
sys_  = c.get('system', {})
nas   = c.get('nas_archive', {})

lines = [
    f"TARGET_USER={q(inst.get('target_user', 'pi'))}",
    f"MNT_DIR={q(inst.get('mount_dir', '/mnt/gadget'))}",
    f"IMG_CAM_NAME={q(disk.get('cam_name', 'usb_cam.img'))}",
    f"IMG_LIGHTSHOW_NAME={q(disk.get('lightshow_name', 'usb_lightshow.img'))}",
    f"IMG_MUSIC_NAME={q(disk.get('music_name', 'usb_music.img'))}",
    f"LABEL1={q(disk.get('cam_label', 'TeslaCam'))}",
    f"LABEL2={q(disk.get('lightshow_label', 'Lightshow'))}",
    f"LABEL3={q(disk.get('music_label', 'Music'))}",
    f"MUSIC_ENABLED={b(disk.get('music_enabled', False))}",
    f"MUSIC_FS={q(disk.get('music_fs', 'fat32'))}",
    f"BOOT_FSCK_ENABLED={b(disk.get('boot_fsck_enabled', True))}",
    f"PART1_SIZE={q(setup.get('part1_size', ''))}",
    f"PART2_SIZE={q(setup.get('part2_size', ''))}",
    f"PART3_SIZE={q(setup.get('part3_size', ''))}",
    f"RESERVE_SIZE={q(setup.get('reserve_size', ''))}",
    f"SAMBA_PASS={q(net.get('samba_password', ''))}",
    f"WEB_PORT={q(net.get('web_port', 80))}",
    f"OFFLINE_AP_ENABLED={b(ap.get('enabled', False))}",
    f"OFFLINE_AP_INTERFACE={q(ap.get('interface', 'wlan0'))}",
    f"OFFLINE_AP_SSID={q(ap.get('ssid', 'TeslaUSB'))}",
    f"OFFLINE_AP_PASSPHRASE={q(ap.get('passphrase', ''))}",
    f"OFFLINE_AP_CHANNEL={q(ap.get('channel', 6))}",
    f"OFFLINE_AP_IPV4_CIDR={q(ap.get('ipv4_cidr', '192.168.4.1/24'))}",
    f"OFFLINE_AP_DHCP_START={q(ap.get('dhcp_start', '192.168.4.10'))}",
    f"OFFLINE_AP_DHCP_END={q(ap.get('dhcp_end', '192.168.4.50'))}",
    f"OFFLINE_AP_CHECK_INTERVAL={q(ap.get('check_interval', 30))}",
    f"OFFLINE_AP_DISCONNECT_GRACE={q(ap.get('disconnect_grace', 60))}",
    f"OFFLINE_AP_MIN_RSSI={q(ap.get('min_rssi', -80))}",
    f"OFFLINE_AP_STABLE_SECONDS={q(ap.get('stable_seconds', 30))}",
    f"OFFLINE_AP_PING_TARGET={q(ap.get('ping_target', '8.8.8.8'))}",
    f"OFFLINE_AP_RETRY_SECONDS={q(ap.get('retry_seconds', 300))}",
    f"OFFLINE_AP_VIRTUAL_IF={q(ap.get('virtual_interface', 'uap0'))}",
    f"OFFLINE_AP_FORCE_MODE={q(ap.get('force_mode', 'force-auto'))}",
    f"CONFIG_FILE={q(sys_.get('config_file', ''))}",
    f"SMB_CONF={q(sys_.get('samba_conf', ''))}",
    f"NAS_ARCHIVE_ENABLED={b(nas.get('enabled', False))}",
    f"NAS_ARCHIVE_HOME_SSID={q(nas.get('home_ssid', ''))}",
    f"NAS_ARCHIVE_SMB_HOST={q(nas.get('smb_host', ''))}",
    f"NAS_ARCHIVE_SMB_SHARE={q(nas.get('smb_share', ''))}",
    f"NAS_ARCHIVE_SMB_USER={q(nas.get('smb_user', ''))}",
    f"NAS_ARCHIVE_SMB_PASSWORD={q(nas.get('smb_password', ''))}",
    f"NAS_ARCHIVE_SMB_VERSION={q(nas.get('smb_version', '2.0'))}",
    f"NAS_ARCHIVE_DELETE_AFTER={b(nas.get('delete_after_archive', False))}",
    f"NAS_ARCHIVE_SLACK_WEBHOOK={q(nas.get('slack_webhook', ''))}",
]
print('\n'.join(lines))
PYEOF
)"

# ============================================================================
# Auto-derive GADGET_DIR from script location (run-in-place)
# This ensures the correct path regardless of username or install location.
# The value in config.yaml is ignored; the actual directory is always used.
# ============================================================================
if [[ "$SCRIPT_DIR_CONFIG" == */scripts ]]; then
  GADGET_DIR="$(dirname "$SCRIPT_DIR_CONFIG")"
else
  GADGET_DIR="$SCRIPT_DIR_CONFIG"
fi

# ============================================================================
# Computed paths (don't modify these)
# ============================================================================
IMG_CAM="$GADGET_DIR/$IMG_CAM_NAME"
IMG_LIGHTSHOW="$GADGET_DIR/$IMG_LIGHTSHOW_NAME"
IMG_MUSIC="$GADGET_DIR/$IMG_MUSIC_NAME"
STATE_FILE="$GADGET_DIR/state.txt"
